### PR TITLE
Add vite example

### PR DESCRIPTION
**Pull request by remcohaszing**
Because examples are built in CI, this means we at least don’t break building with vite.

### CODE REVIEW

**Comment by mhsdesign** [comment]
we need to use es2020 or something for the big ints in vite...

**Comment by remcohaszing** [comment]
Yes I see. It’s unfortunate it doesn’t **just work** for Vite. :(

**Comment by remcohaszing** [comment]
I’m going to merge this, because I’d like to update dependencies and wish to avoid merge conflicts with this branch.

**Comment by mhsdesign** [comment]
Sure ;) Just didn't find the time to test this locally 😄

**Pull request merged**
